In [6]:
import torch

In [7]:
a=torch.rand((3,4))
a

tensor([[0.0244, 0.7617, 0.9439, 0.6414],
        [0.5462, 0.4004, 0.6709, 0.1055],
        [0.2138, 0.7514, 0.3978, 0.5870]])

In [8]:
for l in a:
    print(l)

tensor([0.0244, 0.7617, 0.9439, 0.6414])
tensor([0.5462, 0.4004, 0.6709, 0.1055])
tensor([0.2138, 0.7514, 0.3978, 0.5870])


In [9]:
tensor_0=torch.arange(3,12).view(3,3)
tensor_0

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

# Test for `torch.gather()`

In [10]:
index=torch.tensor([[2,1,0]])
tensor_1=tensor_0.gather(dim=0,index=index)
tensor_1

tensor([[9, 7, 5]])

In [11]:
tensor_2=tensor_0.gather(dim=1,index=index)
tensor_2

tensor([[5, 4, 3]])

In [12]:
a = torch.tensor([[1, 2], [3, 4]])
b = a.gather(dim=0, index=torch.tensor([[0, 1]]))
a, b


(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 4]]))

In [13]:
b=a.gather(dim=0,index=torch.tensor([[0],[1]]))
b

tensor([[1],
        [3]])

In [14]:
c = a.gather(dim=1, index=torch.tensor([[0], [1]]))
c


tensor([[1],
        [4]])

In [15]:
d = a.gather(dim=0, index=torch.tensor([[0, 0], [1, 0]]))
d

tensor([[1, 2],
        [3, 2]])

In [16]:
!nvidia-smi

Mon Jul  4 13:00:58 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:17:00.0 Off |                  N/A |
| 30%   32C    P8    27W / 350W |     13MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:CA:00.0 Off |                  N/A |
| 30%   