In [1]:
import torch

In [2]:
a=torch.rand((3,4))
a

tensor([[0.8784, 0.3016, 0.7000, 0.6504],
        [0.3911, 0.8022, 0.6676, 0.0566],
        [0.9563, 0.3033, 0.1087, 0.0695]])

In [3]:
for l in a:
    print(l)

tensor([0.8784, 0.3016, 0.7000, 0.6504])
tensor([0.3911, 0.8022, 0.6676, 0.0566])
tensor([0.9563, 0.3033, 0.1087, 0.0695])


In [7]:
tensor_0=torch.arange(3,12).view(3,3)
tensor_0

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

# Test for `torch.gather()`

In [10]:
index=torch.tensor([[2,1,0]])
tensor_1=tensor_0.gather(dim=0,index=index)
tensor_1

tensor([[9, 7, 5]])

In [11]:
tensor_2=tensor_0.gather(dim=1,index=index)
tensor_2

tensor([[5, 4, 3]])

In [12]:
a = torch.tensor([[1, 2], [3, 4]])
b = a.gather(dim=0, index=torch.tensor([[0, 1]]))
a, b


(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 4]]))

In [22]:
b=a.gather(dim=0,index=torch.tensor([[0],[1]]))
b

tensor([[1],
        [3]])

In [20]:
c = a.gather(dim=1, index=torch.tensor([[0], [1]]))
c


tensor([[1],
        [4]])

In [18]:
d = a.gather(dim=0, index=torch.tensor([[0, 0], [1, 0]]))
d

tensor([[1, 2],
        [3, 2]])